package Frame;

import VkRender.VkCanvas;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

public class VkGame {
    public JPanel mainPanel;

    public JPanel canvasPanel;
    public JPanel topBar;
    public JPanel bottomBar;
    public JPanel chatPanel;
    public JTextArea chatArea;
    public JTextField chatInput;
    public JPanel SkillPanel;
    public JPanel selectedStatPanel;
    public JButton button1;
    public JButton button2;
    public JButton button3;
    public JButton button4;
    public JButton button5;
    public JButton button6;
    public JButton button7;
    public JButton button8;
    public JButton button9;
    public JButton button10;
    public JButton button11;
    public JButton button12;
    public JButton button13;
    public JButton button14;
    public JButton button15;
    public JButton button16;
    public JProgressBar hpBar;
    public JList selectedUnitList;
    public JLabel unitName;
    public JLabel moneyLabel;

    public JButton[] skillTable;

    private final VkCanvas canvas;

    public VkGame(VkCanvas canvas) {
        super();
        this.canvas = canvas;
    }

    public void createUIComponents() {
        canvasPanel.add(canvas);
        skillTable = new JButton[]{
                button1, button2, button3, button4,
                button5, button6, button7, button8,
                button9, button10, button11, button12,
                button13, button14, button15, button16,
        };
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.setName("mainPanel");
        topBar = new JPanel();
        topBar.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        topBar.setMaximumSize(new Dimension(2147483647, 20));
        topBar.setMinimumSize(new Dimension(24, 20));
        topBar.setName("");
        topBar.setPreferredSize(new Dimension(24, 20));
        mainPanel.add(topBar, BorderLayout.NORTH);
        moneyLabel = new JLabel();
        moneyLabel.setText("0");
        moneyLabel.setToolTipText("Money");
        topBar.add(moneyLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        topBar.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        canvasPanel = new JPanel();
        canvasPanel.setLayout(new BorderLayout(0, 0));
        canvasPanel.setMinimumSize(new Dimension(600, 400));
        canvasPanel.setName("");
        canvasPanel.setPreferredSize(new Dimension(800, 600));
        mainPanel.add(canvasPanel, BorderLayout.CENTER);
        bottomBar = new JPanel();
        bottomBar.setLayout(new BorderLayout(0, 0));
        bottomBar.setAutoscrolls(false);
        bottomBar.setMaximumSize(new Dimension(2147483647, 500));
        bottomBar.setMinimumSize(new Dimension(-1, 100));
        bottomBar.setPreferredSize(new Dimension(-1, 200));
        mainPanel.add(bottomBar, BorderLayout.SOUTH);
        chatPanel = new JPanel();
        chatPanel.setLayout(new BorderLayout(0, 0));
        chatPanel.setMaximumSize(new Dimension(500, 2147483647));
        chatPanel.setMinimumSize(new Dimension(100, -1));
        chatPanel.setName("");
        chatPanel.setPreferredSize(new Dimension(300, -1));
        chatPanel.setRequestFocusEnabled(true);
        bottomBar.add(chatPanel, BorderLayout.WEST);
        chatArea = new JTextArea();
        chatArea.setEditable(false);
        chatPanel.add(chatArea, BorderLayout.CENTER);
        chatInput = new JTextField();
        chatPanel.add(chatInput, BorderLayout.SOUTH);
        SkillPanel = new JPanel();
        SkillPanel.setLayout(new GridBagLayout());
        SkillPanel.setMinimumSize(new Dimension(200, 92));
        SkillPanel.setPreferredSize(new Dimension(200, 0));
        bottomBar.add(SkillPanel, BorderLayout.EAST);
        button1 = new JButton();
        button1.setEnabled(false);
        button1.setPreferredSize(new Dimension(50, 50));
        button1.setText("Button");
        button1.setToolTipText("");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        SkillPanel.add(button1, gbc);
        button2 = new JButton();
        button2.setEnabled(false);
        button2.setPreferredSize(new Dimension(50, 50));
        button2.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        SkillPanel.add(button2, gbc);
        button3 = new JButton();
        button3.setEnabled(false);
        button3.setPreferredSize(new Dimension(50, 50));
        button3.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        SkillPanel.add(button3, gbc);
        button4 = new JButton();
        button4.setEnabled(false);
        button4.setPreferredSize(new Dimension(50, 50));
        button4.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        SkillPanel.add(button4, gbc);
        button5 = new JButton();
        button5.setEnabled(false);
        button5.setPreferredSize(new Dimension(50, 50));
        button5.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        SkillPanel.add(button5, gbc);
        button6 = new JButton();
        button6.setEnabled(false);
        button6.setPreferredSize(new Dimension(50, 50));
        button6.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        SkillPanel.add(button6, gbc);
        button7 = new JButton();
        button7.setEnabled(false);
        button7.setPreferredSize(new Dimension(50, 50));
        button7.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        SkillPanel.add(button7, gbc);
        button8 = new JButton();
        button8.setEnabled(false);
        button8.setPreferredSize(new Dimension(50, 50));
        button8.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        SkillPanel.add(button8, gbc);
        button9 = new JButton();
        button9.setEnabled(false);
        button9.setPreferredSize(new Dimension(50, 50));
        button9.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        SkillPanel.add(button9, gbc);
        button10 = new JButton();
        button10.setEnabled(false);
        button10.setPreferredSize(new Dimension(50, 50));
        button10.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        SkillPanel.add(button10, gbc);
        button11 = new JButton();
        button11.setEnabled(false);
        button11.setPreferredSize(new Dimension(50, 50));
        button11.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        SkillPanel.add(button11, gbc);
        button12 = new JButton();
        button12.setEnabled(false);
        button12.setPreferredSize(new Dimension(50, 50));
        button12.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        SkillPanel.add(button12, gbc);
        button13 = new JButton();
        button13.setEnabled(false);
        button13.setPreferredSize(new Dimension(50, 50));
        button13.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        SkillPanel.add(button13, gbc);
        button14 = new JButton();
        button14.setEnabled(false);
        button14.setPreferredSize(new Dimension(50, 50));
        button14.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        SkillPanel.add(button14, gbc);
        button15 = new JButton();
        button15.setEnabled(false);
        button15.setPreferredSize(new Dimension(50, 50));
        button15.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        SkillPanel.add(button15, gbc);
        button16 = new JButton();
        button16.setEnabled(false);
        button16.setPreferredSize(new Dimension(50, 50));
        button16.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        SkillPanel.add(button16, gbc);
        selectedStatPanel = new JPanel();
        selectedStatPanel.setLayout(new BorderLayout(0, 0));
        selectedStatPanel.setAlignmentY(0.5f);
        selectedStatPanel.setMaximumSize(new Dimension(300, 2147483647));
        selectedStatPanel.setMinimumSize(new Dimension(200, 0));
        selectedStatPanel.setPreferredSize(new Dimension(300, 0));
        bottomBar.add(selectedStatPanel, BorderLayout.CENTER);
        hpBar = new JProgressBar();
        hpBar.setAlignmentX(0.5f);
        hpBar.setAlignmentY(0.5f);
        hpBar.setName("");
        hpBar.setPreferredSize(new Dimension(219, 20));
        hpBar.setString("0 / 0");
        hpBar.setStringPainted(true);
        selectedStatPanel.add(hpBar, BorderLayout.SOUTH);
        selectedUnitList = new JList();
        selectedUnitList.setDoubleBuffered(false);
        selectedUnitList.setDragEnabled(false);
        selectedUnitList.setFixedCellHeight(30);
        selectedUnitList.setFixedCellWidth(30);
        selectedUnitList.setLayoutOrientation(2);
        selectedUnitList.setMaximumSize(new Dimension(-1, 90));
        selectedUnitList.setMinimumSize(new Dimension(30, 30));
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        defaultListModel1.addElement("1");
        defaultListModel1.addElement("2");
        defaultListModel1.addElement("3");
        defaultListModel1.addElement("4");
        defaultListModel1.addElement("5");
        defaultListModel1.addElement("6");
        defaultListModel1.addElement("7");
        defaultListModel1.addElement("8");
        defaultListModel1.addElement("9");
        defaultListModel1.addElement("10");
        defaultListModel1.addElement("11");
        defaultListModel1.addElement("12");
        defaultListModel1.addElement("13");
        selectedUnitList.setModel(defaultListModel1);
        selectedUnitList.setOpaque(true);
        selectedUnitList.setPreferredSize(new Dimension(-1, 90));
        selectedUnitList.setSelectedIndex(0);
        selectedUnitList.setSelectionMode(0);
        selectedUnitList.setValueIsAdjusting(false);
        selectedUnitList.setVisibleRowCount(1);
        selectedStatPanel.add(selectedUnitList, BorderLayout.NORTH);
        unitName = new JLabel();
        unitName.setText("Label");
        selectedStatPanel.add(unitName, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
